import {
  AlertTriangle,
  Bell,
  CheckCircle2,
  Clock,
  FileCheck,
  FileText,
  Layers,
  RefreshCw,
  Search,
  Send,
  ShieldAlert,
} from "lucide-react";

export const SLA_LIFECYCLE_STEPS = [
  {
    step: 1,
    key: "SLA_THRESHOLD_REACHED",
    title: "SLA Threshold Reached",
    desc: "Warning or breach deadline reached",
    icon: Clock,
  },
  {
    step: 2,
    key: "GRIEVANCE_ESCALATED",
    title: "Grievance Escalated",
    desc: "Status moves to Escalated, severity flagged",
    icon: AlertTriangle,
  },
  {
    step: 3,
    key: "HOD_NOTIFIED",
    title: "Department Head Notified",
    desc: "Urgent alert banner dispatched to HOD portal",
    icon: Bell,
  },
  {
    step: 4,
    key: "UNDER_REVIEW",
    title: "Head Reviews Grievance",
    desc: "HOD inspects details, timeline & history",
    icon: Search,
  },
  {
    step: 5,
    key: "BOTTLENECK_IDENTIFIED",
    title: "Identifies Bottleneck",
    desc: "Pinpoints root stall: staff, cross-dept, or docs",
    icon: Layers,
  },
  {
    step: 6,
    key: "INTERVENTION_TAKEN",
    title: "Takes Intervention Action",
    desc: "Reassigns, cross-dept, expedites, or overrides",
    icon: ShieldAlert,
  },
  {
    step: 7,
    key: "AUDIT_LOGGED",
    title: "Action Logged in Audit Trail",
    desc: "Immutable timestamped governance entry",
    icon: FileText,
  },
  {
    step: 8,
    key: "STAFF_NOTIFIED",
    title: "Staff / Dept Notified",
    desc: "Operational directives dispatched to team",
    icon: Send,
  },
  {
    step: 9,
    key: "IN_PROGRESS",
    title: "Grievance Continues",
    desc: "Investigation resumes under active intervention",
    icon: RefreshCw,
  },
  {
    step: 10,
    key: "RESOLUTION_SUBMITTED",
    title: "Resolution Submitted",
    desc: "Investigating officer submits solution note",
    icon: FileCheck,
  },
  {
    step: 11,
    key: "ESCALATION_CLEARED",
    title: "Escalation Cleared",
    desc: "HOD reviews, approves & closes grievance",
    icon: CheckCircle2,
  },
];
